name: CD Pipeline

on:
  workflow_run:
    workflows: ["Run Tests"]
    branches: [main]
    types: 
      - completed

jobs:
  cd:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Notify deployment success
        run: echo "Deployment successful!"