name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    branches: [main]
    types:
      - completed

jobs:
  docker_build_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "frontend"
          push: true
          tags: ghcr.io/chesterchutw/testing-lab-frontend:${{ github.sha }}

  docker_build_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "./backend"
          push: true
          tags: ghcr.io/chesterchutw/testing-lab-backend:${{ github.sha }}

  kubernetes_deploy:
    needs: [docker_build_frontend, docker_build_backend]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.20.2/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Update image tags in deploys.yaml
        run: |
          yq eval -i '(.spec.template.spec.containers[] | select(.name == "testing-lab-backend") | .image) = "ghcr.io/chesterchutw/testing-lab-backend:${{ github.sha }}"' ./k8s/deploys.yaml
          yq eval -i '(.spec.template.spec.containers[] | select(.name == "testing-lab-frontend") | .image) = "ghcr.io/chesterchutw/testing-lab-frontend:${{ github.sha }}"' ./k8s/deploys.yaml

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: "latest"

      - name: Configure kubectl
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: echo "${KUBECONFIG}" > $HOME/.kube/config

      - name: Debug
        run: |
          cat $HOME/.kube/config
          kubectl get pods

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ./k8s/deploys.yaml
          kubectl apply -f ./k8s/services.yaml
          kubectl apply -f ./k8s/ingress.yaml
