name: CD Pipeline

# on:
#   workflow_run:
#     workflows: ["CI Pipeline"]
#     branches: [main]
#     types: 
#       - completed

on:
  pull_request:
    branches:
      - main

jobs:
  cd:
    name: Deploy Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Notify deployment success
        run: echo "Deployment successful!"