name: CI Pipeline

on:
  push:
    branches:
      - "**"

jobs:
  coverage_check:
    name: Unit Test and Coverage Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 ## 0: 取得所有紀錄, 1: 僅取得最新紀錄

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies (frontend)
        run: |
          cd frontend
          npm install

      - name: Install dependencies (backend)
        run: |
          cd backend
          npm install

      - name: Run unit tests (frontend)
        run: |
          cd frontend
          npm run cy:test

      - name: Run unit tests (backend) and Generate new coverage report
        run: |
          cd backend
          npm run test --coverage
          node ./coverage-compare/calculateCoverage.js

      - name: Check and compare coverage
        run: node backend/coverage-compare/checkCoverage.js

      - name: Upload coverage summary as old coverage
        if: success()
        run: |
          cd backend/coverage-compare
          mv coverage-summary.json coverage-summary-old.json
          cat coverage-summary-old.json
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.name "ChesterChuTw"
            git config --global user.email "chester850117@gmail.com"
            git add .
            git commit -m "chore: update coverage summary"
            git push https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
          fi

      - name: Upload coverage summary to artifacts for further review
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-summary
          path: backend/coverage-compare/coverage-summary-old.json

  auto_format:
    name: Auto Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 ## 0: 取得所有紀錄, 1: 僅取得最新紀錄

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Run Prettier for backend
        run: |
          cd backend
          npx prettier --write .
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.name "ChesterChuTw"
            git config --global user.email "chester850117@gmail.com"
            git add .
            git commit -m "chore: format backend code with Prettier"
            git push https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
          fi

      - name: Run Prettier for frontend
        run: |
          cd frontend
          npx prettier --write .
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.name "ChesterChuTw"
            git config --global user.email "chester850117@gmail.com"
            git add .
            git commit -m "chore: format frontend code with Prettier"
            git push https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
          fi
