name: CI Pipeline

on:
  push: 
    branches:
      - '*'

jobs:
  ci:
    name: Run CI Tests and Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # 0: 取得所有紀錄, 1: 僅取得最新紀錄