name: CI Pipeline

on:
  push:
    branches:
      - '**'

jobs:
  ci:
    name: Run CI Tests and Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # 0: 取得所有紀錄, 1: 僅取得最新紀錄

      - name: Run Prettier for backend
        run: |
          cd backend
          npx prettier --write .
          git config --global user.name "github-runner"
          git config --global user.email "github-runner@github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "chore: format backend code with Prettier"
            git push
          fi

      - name: Run Prettier for frontend
        run: |
          cd frontend
          npx prettier --write .
          git config --global user.name "github-runner"
          git config --global user.email "github-runner@github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "chore: format frontend code with Prettier"
            git push
          fi
