name: CI Pipeline

on:
  push:
    branches:
      - '**'

jobs:
  ci:
    name: Run CI Tests and Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # 0: 取得所有紀錄, 1: 僅取得最新紀錄

      - name: Run Prettier for backend
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          cd backend
          npx prettier --write .
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.name "github-runner"
            git config --global user.email "github-runner@github.com"
            git add .
            git commit -m "chore: format backend code with Prettier"
            git push https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
          fi

      - name: Run Prettier for frontend
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          cd frontend
          npx prettier --write .
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.name "ChesterChuTw"
            git config --global user.email "chester850117@gmail.com"
            git add .
            git commit -m "chore: format frontend code with Prettier"
            git push https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
          fi
